on: [push, pull_request]

name: Cache-Lite.Rust

defaults:
  run:
    working-directory: Cache-Lite.Rust

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: moonrepo/setup-rust@v1
      - run: cargo clippy -- -D warnings

  test:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: moonrepo/setup-rust@v1
      - run: cargo test

  build:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: moonrepo/setup-rust@v1
      - run: cargo build