on: [push, pull_request]

name: Cache-Lite.Rust

defaults:
  run:
    working-directory: Cache-Lite.Rust

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: moonrepo/setup-rust@v1

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build